spring:
  #mongodb database
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: db_student
      uri: mongodb://dbstudentadm:dbstudentadm@127.0.0.1:27017/db_student?authSource=admin
           #"mongodb://dbstudentadm:dbstudentadm@127.0.0.1:27017/db_student?authMechanism=DEFAULT"
      authentication-database: dbstudentadm
      username: dbstudentadm
      password: dbstudentadm

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus


#custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /swaggerui.html
    operationsSorter: alpha
    tagsSorter: alpha

  # custom path for api docs
  api-docs:
    path: /api-docs

