version: '3.8'
services:

  #MongoDB
  #url de conexao:
  # mongodb://dbstudentadm:dbstudentadm@127.0.0.1:27017/dbstudent?authMechanism=DEFAULT
  mongodb:
    image: mongo:${DB_MONGO_VERSION}
    container_name: local-mongo-db-${DB_MONGO_VERSION}
    hostname: localhost
    restart: always
    volumes:
      - ./mongodb/config/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb/mongodb-data:/data/db/
      - ./mongodb/mongodb-log:/var/log/mongodb/
      
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - stack1-network

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log
  
networks:
  stack1-network:
    driver: bridge  